Esquemas={
    "generos": ["Accion", "Aventura", "Sci-Fi", "Fantasia", "Terror", "Suspense", "Drama", "Comedia", "Romance", "Misterio", "Crimen", "Western", "Belica", "Animacion", "Musical", "Documental", "Deportes", "Familiar", "Historica", "Experimental", "Biografica", "Noir", "Superheroes", "Catastrofes", "Road Movie", "Indie"],
    "subgeneros": ["Cyberpunk", "Steampunk", "Space Opera", "Distopia", "Utopia", "Postapocaliptica", "Fantasia Oscura", "Fantasia Urbana", "Fantasia Epica", "Slasher", "Gore", "Body Horror", "Found Footage", "Terror Psicologico", "Terror Sobrenatural", "Terror Cosmico", "Thriller Psicologico", "Thriller Politico", "Thriller Criminal", "Thriller Legal", "Thriller Tecnologico", "Comedia Romantica", "Comedia Negra", "Parodia", "Satira", "Drama Familiar", "Drama Historico", "Drama Social", "Drama Judicial", "Drama Belico", "Romance Historico", "Romance Adolescente", "Detectives", "Neo-Noir", "Mafia", "Gangsters", "Atracos", "Espionaje", "Artes Marciales", "Samurais", "Wuxia", "Spaghetti Western", "Kaiju", "Anime", "Stop Motion", "True Crime"],
    "tematicas": ["Amor", "Amistad", "Familia", "Venganza", "Justicia", "Libertad", "Superacion", "Supervivencia", "Poder", "Corrupcion", "Politica", "Guerra", "Paz", "Sacrificio", "Redencion", "Perdon", "Esperanza", "Muerte", "Duelo", "Destino", "Identidad", "Autodescubrimiento", "Madurez", "Racismo", "Discriminacion", "Esclavitud", "Religion", "Fe", "Mitologia", "Tecnologia", "Inteligencia Artificial", "Humanidad", "Inmortalidad", "Vida Extraterrestre", "Viajes en el Tiempo", "Apocalipsis", "Conquista", "Vida y Muerte", "Lealtad", "Traicion", "Codicia", "Ambicion", "Crimen", "Vigilantismo", "Revolucion", "Resistencia", "Ecologia", "Cambio Climatico", "Educacion", "Deporte", "Adiccion"],
    "ambientacion": ["Espacio", "Ciudad", "Pueblo", "Desierto", "Selva", "Bosque", "Montana", "Oceano", "Isla", "Instituto", "Universidad", "Hospital", "Prision", "Mundo Fantastico", "Castillo", "Planeta Alienigena", "Nave Espacial", "Base Militar", "Mansion", "Suburbios", "Metropoli", "Inframundo Criminal", "Mundo Virtual", "Ciberespacio", "Apocalipsis", "Postapocalipsis"],
    "epoca": ["Prehistoria", "Antiguedad", "Imperio Romano", "Edad Media", "Renacimiento", "Siglo XVII", "Siglo XVIII", "Siglo XIX", "Epoca Victoriana", "Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra Fria", "Anos 50", "Anos 60", "Anos 70", "Anos 80", "Anos 90", "Actualidad", "Futuro Cercano", "Futuro Lejano"],
    "tono": ["Oscuro", "Serio", "Violento", "Epico", "Emotivo", "Inspirador", "Humoristico", "Humor Negro", "Sardonico", "Melancolico", "Reflexivo", "Esperanzador", "Pesimista", "Tenso", "Desgarrador", "Ligero", "Alegre", "Brutal", "Realista", "Surrealista", "Absurdo"],
    "personajes": ["Heroe", "Antiheroe", "Villano", "Detective", "Policia", "Criminal", "Asesino", "Ganster", "Cazarrecompensas", "Superheroe", "Supervillano", "Rebelde", "Elegido", "Mentor", "Huerfano", "Rey", "Reina", "Principe", "Princesa", "Soldado", "Espia", "Pirata", "Samurai", "Ninja", "Mago", "Bruja", "Alienigena", "Robot", "Cientifico", "Estudiante", "Deportista", "Doctor", "Abogado", "Politico", "Vampiro", "Hombre Lobo", "Zombie"],
    "elementos": ["Magia", "Dragones", "Espadas", "Pistoleros", "Duelo", "Atracos", "Persecuciones", "Explosiones", "Armas Futuristas", "Robots", "Androides", "IA", "Extraterrestres", "Naves Espaciales", "Portales", "Viajes en el Tiempo", "Universos Paralelos", "Superpoderes", "Monstruos", "Kaijus", "Zombies", "Vampiros", "Hombres Lobo", "Fantasmas", "Casas Encantadas", "Tesoros", "Supervivencia", "Investigacion", "Juicios", "Conspiraciones", "Pandemias", "Apocalipsis", "Postapocalipsis", "Artes Marciales", "Carreras", "Deportes", "Musica", "Baile"],
    "emociones": ["Diversion", "Felicidad", "Tristeza", "Tension", "Miedo", "Suspense", "Asombro", "Nostalgia", "Esperanza", "Inspiracion", "Empatia", "Intriga", "Adrenalina", "Melancolia", "Euforia", "Ansiedad", "Impacto", "Satisfaccion", "Ternura", "Romance"],
    "publico": ["Infantil", "Familiar", "Juvenil", "Adolescentes", "Adultos", "Todos los  Publicos"]

}